name: Build Windows 2019  Tools Cache
on: workflow_dispatch
jobs:
  build_tool_cache:
    runs-on: self-hosted
    steps:    
      - name: Clear any existing tool cache
        run: |
          rm "${{ runner.tool_cache }}" -r -force
        
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.11.x'

      - name: Setup Node 10
        uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: Setup Node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'    
          java-version: '17'

      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf windows_2019_tool_cache.tar.gz *

      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{runner.tool_cache}}/windows_2019_tool_cache.tar.gz

