---
name: Download dotnet for Linux
on: workflow_dispatch
jobs:
  build_tool_cache:
    runs-on: Linux
    steps:    
          
      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          dotnet-version: 8.x
