name: RHEL 7.9 Tool Cache
on: workflow_dispatch
jobs:
  build_tool_cache:
    runs-on: linux
    steps:    
      - name: Clear any existing tool cache
        run: |
          rm -rf "${{ runner.tool_cache }}" 
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'            # need to select our distribution
          java-version: '17'
